version: "3"

services:
  app:
    build: ./app/
    image: ml-service-app:0.1
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy

  celery-validation-worker:
    build: ./app/
    working_dir: /app/src
    image: ml-service-app:0.1
    command: celery -A celery_worker.celery worker --loglevel=info --logfile=logs/celery.log -Q validation
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - app
      - rabbitmq
    deploy:
      replicas: 2

  celery-prediction-worker:
    build: ./app/
    working_dir: /app/src
    image: ml-service-app:0.1
    command: celery -A celery_worker.celery worker --loglevel=info --logfile=logs/celery.log -Q prediction
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - app
      - rabbitmq
    deploy:
      replicas: 3

  web-proxy:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - db

  rabbitmq:
    image: rabbitmq:4-management-alpine
    hostname: rabbitmq
    restart: on-failure
    env_file:
      - .env
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
  rabbitmq_volume:
